### ISSUE TITLE
Default English Language

### ISSUE THREAD

**Issue by 3xploiton3** [WinUICommunity/TvTime#6]
in my case, its annoying to remove 1 by 1 another language that doesnt relevance to me

i'm using english & indonesian language

![image](https://github.com/WinUICommunity/TvTime/assets/19517680/26a241a3-f2a7-45cf-98c2-b4d8b3ae5faa)

_Originally posted by @3xploiton3 in https://github.com/WinUICommunity/TvTime/issues/4#issuecomment-1663550818_

**Comment by ghost1372** [comment]
Tnx for Suggestion @3xploiton3 
You can now enable or disable languages you need by selecting on it.
By default, 2 languages, Persian and English are selected.
The ability to add and remove languages has been removed. This is because we can't add any language we want, we only support the languages that subscene supports.
![Screenshot 2023-08-04 141441](https://github.com/WinUICommunity/TvTime/assets/9213496/3b231754-f258-4aff-97ab-f12929ddbcfc)
